exception.default_message=Internal error. Please try later or contact support service.
exception.book.already_exists=Book with same data already exists
exception.book.not_found_by_id=Book not found
